name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    required: true
    description: "Who to greet"
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

  branding:
    icon: "mic"
    color: "purple"
